name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install MPI
      run: |
        sudo apt update
        sudo apt install -y -q mpich libmpich-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        pip install mpi4py
        pip install pylint
        pip install sympy
        pip install mpmath
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files ':(glob)src/*.py') --fail-under=5.0 --disable=C0411,C0116,C0114,C0413
